// <auto-generated />
using System;
using Co_ParentingApp.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Co_ParentingApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260112235214_AddMatchedMembersTablev2")]
    partial class AddMatchedMembersTablev2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Co_ParentingApp.Data.Models.EntityModels.MatchedMemberEntity", b =>
                {
                    b.Property<Guid>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MatchedMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MatchingMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("MatchId");

                    b.HasIndex("MatchedMemberId");

                    b.HasIndex("MatchingMemberId", "MatchedMemberId")
                        .IsUnique();

                    b.ToTable("MatchedMembers", (string)null);
                });

            modelBuilder.Entity("Co_ParentingApp.Data.Models.EntityModels.MemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PairingKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pairing_key");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("Member", (string)null);
                });

            modelBuilder.Entity("Co_ParentingApp.Data.Models.EntityModels.MatchedMemberEntity", b =>
                {
                    b.HasOne("Co_ParentingApp.Data.Models.EntityModels.MemberEntity", null)
                        .WithMany()
                        .HasForeignKey("MatchedMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Co_ParentingApp.Data.Models.EntityModels.MemberEntity", null)
                        .WithMany()
                        .HasForeignKey("MatchingMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
