// <auto-generated />
using System;
using Co_ParentingApp.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Co_ParentingApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260126112731_AddLastReadAt")]
    partial class AddLastReadAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Co_ParentingApp.Data.Models.EntityModels.ConversationEntity", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConversationId");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("Co_ParentingApp.Data.Models.EntityModels.ConversationMembersEntity", b =>
                {
                    b.Property<Guid>("ConversationMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.HasKey("ConversationMemberId");

                    b.HasIndex("MemberId");

                    b.HasIndex("ConversationId", "MemberId")
                        .IsUnique();

                    b.ToTable("ConversationMembers", (string)null);
                });

            modelBuilder.Entity("Co_ParentingApp.Data.Models.EntityModels.MatchedMemberEntity", b =>
                {
                    b.Property<Guid>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MatchedMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MatchingMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("MatchId");

                    b.HasIndex("MatchedMemberId");

                    b.HasIndex("MatchingMemberId", "MatchedMemberId")
                        .IsUnique();

                    b.ToTable("MatchedMembers", (string)null);
                });

            modelBuilder.Entity("Co_ParentingApp.Data.Models.EntityModels.MemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PairingKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pairing_key");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("Member", (string)null);
                });

            modelBuilder.Entity("Co_ParentingApp.Data.Models.EntityModels.MessageEntity", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("Co_ParentingApp.Data.Models.EntityModels.ConversationMembersEntity", b =>
                {
                    b.HasOne("Co_ParentingApp.Data.Models.EntityModels.ConversationEntity", "Conversation")
                        .WithMany("Members")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Co_ParentingApp.Data.Models.EntityModels.MemberEntity", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Co_ParentingApp.Data.Models.EntityModels.MatchedMemberEntity", b =>
                {
                    b.HasOne("Co_ParentingApp.Data.Models.EntityModels.MemberEntity", "MatchedMember")
                        .WithMany()
                        .HasForeignKey("MatchedMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Co_ParentingApp.Data.Models.EntityModels.MemberEntity", "MatchingMember")
                        .WithMany()
                        .HasForeignKey("MatchingMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MatchedMember");

                    b.Navigation("MatchingMember");
                });

            modelBuilder.Entity("Co_ParentingApp.Data.Models.EntityModels.MessageEntity", b =>
                {
                    b.HasOne("Co_ParentingApp.Data.Models.EntityModels.ConversationEntity", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Co_ParentingApp.Data.Models.EntityModels.MemberEntity", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Co_ParentingApp.Data.Models.EntityModels.ConversationEntity", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
